import thinky   from '../lib/thinky';

const type = thinky.type;

const Category = thinky.createModel('Category', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Category.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Category.ensureIndex('name');
Category.ensureIndex('createdAt');
Category.ensureIndex('editedAt');

Category.associate = models => {
    models.Category.hasMany(models.Article, 'articles', 'id', 'categoryId');
};

export default Category;
