import thinky from '../lib/thinky';

const type = thinky.type;

const Device = thinky.createModel('Device', {
    // Optional => not specified in bodies but generated by RethinkDB
    id              : type.string().optional(),
    fingerprint     : String,
    name            : String,
    doubleValidation: type.boolean().default(false),
    offlineSupport  : type.boolean().default(false),
    alcohol         : type.boolean().default(false),
    showPicture     : type.boolean().default(false),
    createdAt       : type.date().default(new Date()),
    editedAt        : Date,
    isRemoved       : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Device.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Device.ensureIndex('name');
Device.ensureIndex('createdAt');
Device.ensureIndex('editedAt');
Device.ensureIndex('fingerprint');

Device.associate = models => {
    models.Device.hasAndBelongsToMany(models.PeriodPoint, 'periodPoints', 'id', 'id');
};

export default Device;
