import thinky from '../thinky';

const type = thinky.type;

const Fundation = thinky.createModel('Fundation', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    website  : String,
    mail     : String,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Fundation.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Fundation.ensureIndex('name');
Fundation.ensureIndex('createdAt');
Fundation.ensureIndex('editedAt');

Fundation.associate = models => {
    models.Fundation.hasMany(models.Price, 'prices', 'id', 'Fundation_id');
    models.Fundation.hasMany(models.Purchase, 'purchases', 'id', 'Fundation_id');
};

export default Fundation;
