const thinky = require('../lib/thinky');

const type = thinky.type;

const Fundation = thinky.createModel('Fundation', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    website  : type.string().optional(),
    mail     : type.string().optional(),
    createdAt: type.date().default(() => new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Fundation.pre('save', function preSave(next) {
    this.editedAt = new Date();
    next();
});

Fundation.ensureIndex('name');
Fundation.ensureIndex('createdAt');
Fundation.ensureIndex('editedAt');

Fundation.associate = (models) => {
    models.Fundation.hasMany(models.Price, 'prices', 'id', 'Fundation_id');
};

module.exports = Fundation;
