import thinky from '../lib/thinky';

const type = thinky.type;

const GroupPeriod = thinky.createModel('GroupPeriod', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    Period_id: type.string().optional(),
    Group_id : type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

GroupPeriod.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

GroupPeriod.ensureIndex('createdAt');
GroupPeriod.ensureIndex('editedAt');

GroupPeriod.associate = models => {
    models.GroupPeriod.belongsTo(models.Group, 'Group', 'Group_id', 'id');
    models.GroupPeriod.belongsTo(models.Period, 'period', 'Period_id', 'id');
    models.GroupPeriod.hasAndBelongsToMany(models.User, 'users', 'id', 'id');
};

export default GroupPeriod;
