import thinky from '../lib/thinky';

const type = thinky.type;

const Group = thinky.createModel('Group', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isOpen   : type.boolean().default(true),
    isPublic : type.boolean().default(false),
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Group.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Group.ensureIndex('name');
Group.ensureIndex('createdAt');
Group.ensureIndex('editedAt');

Group.associate = models => {
    models.Group.hasAndBelongsToMany(models.User, 'users', 'id', 'id');
    models.Group.hasMany(models.Price, 'prices', 'id', 'Group_id');
};

export default Group;
