import thinky from '../lib/thinky';

const type = thinky.type;

const MeanOfPayment = thinky.createModel('MeanOfPayment', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    slug     : type.string(),
    name     : type.string(),
    step     : type.number().default(100),
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

MeanOfPayment.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

MeanOfPayment.ensureIndex('createdAt');
MeanOfPayment.ensureIndex('editedAt');

MeanOfPayment.associate = () => {};

export default MeanOfPayment;
