import thinky   from '../lib/thinky';

const type = thinky.type;

const Period = thinky.createModel('Period', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    start    : Date,
    end      : Date,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Period.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Period.ensureIndex('name');
Period.ensureIndex('start');
Period.ensureIndex('end');
Period.ensureIndex('createdAt');
Period.ensureIndex('editedAt');

Period.associate = models => {
    models.Period.hasMany(models.PeriodPoint, 'periodPoints', 'id', 'periodId');
    models.Period.hasMany(models.Price, 'prices', 'id', 'periodId');
    models.Period.hasMany(models.Right, 'rights', 'id', 'periodId');
};

export default Period;
