import thinky from '../lib/thinky';

const type = thinky.type;

const Promotion = thinky.createModel('Promotion', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    Price_id : type.string().optional(),
    Point_id : type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Promotion.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Promotion.ensureIndex('name');
Promotion.ensureIndex('createdAt');
Promotion.ensureIndex('editedAt');

Promotion.associate = models => {
    models.Promotion.belongsTo(models.Point, 'point', 'Point_id', 'id');
    models.Promotion.hasAndBelongsToMany(models.Price, 'prices', 'id', 'id');
    // n:n instead of 1:n to allow one promotion containing multiple times the same article
    models.Promotion.hasAndBelongsToMany(models.Article, 'articles', 'id', 'id');
    // n:n instead of 1:n to allow one promotion containing multiple times the same set
    models.Promotion.hasAndBelongsToMany(models.Set, 'sets', 'id', 'id');
    models.Promotion.hasMany(models.Purchase, 'purchases', 'id', 'Promotion_id');
};

export default Promotion;
