import thinky from '../thinky';

const type = thinky.type;

const Purchase = thinky.createModel('Purchase', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    createdAt  : type.date().default(new Date()),
    editedAt   : Date,
    isRemoved  : type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    buyerId    : type.string().optional(),
    fundationId: type.string().optional(),
    pointId    : type.string().optional(),
    promotionId: type.string().optional(),
    sellerId   : type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Purchase.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Purchase.ensureIndex('ip');
Purchase.ensureIndex('price');
Purchase.ensureIndex('createdAt');
Purchase.ensureIndex('editedAt');

Purchase.associate = models => {
    models.Purchase.belongsTo(models.Fundation, 'fundation', 'fundationId', 'id');
    models.Purchase.belongsTo(models.Point, 'point', 'pointId', 'id');
    models.Purchase.belongsTo(models.Promotion, 'promotion', 'promotionId', 'id');
    models.Purchase.belongsTo(models.User, 'buyer', 'buyerId', 'id');
    models.Purchase.belongsTo(models.User, 'seller', 'sellerId', 'id');
    models.Purchase.hasAndBelongsToMany(models.Article, 'articles', 'id', 'id');
};

export default Purchase;
