const thinky = require('../lib/thinky');

const type = thinky.type;

const Reload = thinky.createModel('Reload', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    credit   : Number,
    type     : String,
    trace    : String,
    createdAt: type.date().default(() => new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    Point_id : type.string().optional(),
    Buyer_id : type.string().optional(),
    Seller_id: type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Reload.pre('save', function preSave(next) {
    this.editedAt = new Date();
    next();
});

Reload.ensureIndex('ip');
Reload.ensureIndex('credit');
Reload.ensureIndex('trace');
Reload.ensureIndex('createdAt');
Reload.ensureIndex('editedAt');

Reload.associate = (models) => {
    models.Reload.belongsTo(models.Point, 'point', 'Point_id', 'id');
    models.Reload.belongsTo(models.User, 'buyer', 'Buyer_id', 'id');
    models.Reload.belongsTo(models.User, 'seller', 'Seller_id', 'id');
};

module.exports = Reload;
