import thinky from '../thinky';

const type = thinky.type;

const Reload = thinky.createModel('Reload', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    credit   : Number,
    // Trace ~= type
    trace    : String,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    pointId  : type.string().optional(),
    buyerId  : type.string().optional(),
    sellerId : type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Reload.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Reload.ensureIndex('ip');
Reload.ensureIndex('credit');
Reload.ensureIndex('trace');
Reload.ensureIndex('createdAt');
Reload.ensureIndex('editedAt');

Reload.associate = models => {
    models.Reload.belongsTo(models.Point, 'point', 'pointId', 'id');
    models.Reload.belongsTo(models.User, 'buyer', 'buyerId', 'id');
    models.Reload.belongsTo(models.User, 'seller', 'sellerId', 'id');
};

export default Reload;
