import thinky from '../lib/thinky';

const type = thinky.type;

const Right = thinky.createModel('Right', {
    // Optional => not specified in bodies but generated by RethinkDB
    id       : type.string().optional(),
    name     : String,
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    Period_id: type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Right.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Right.ensureIndex('name');
Right.ensureIndex('createdAt');
Right.ensureIndex('editedAt');

Right.associate = models => {
    models.Right.belongsTo(models.Period, 'period', 'Period_id', 'id');
    models.Right.hasAndBelongsToMany(models.User, 'users', 'id', 'id');
};

export default Right;
