import thinky from '../lib/thinky';

const type = thinky.type;

const Transfer = thinky.createModel('Transfer', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    amount     : Number,
    createdAt  : type.date().default(new Date()),
    editedAt   : Date,
    isRemoved  : type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    Sender_id  : type.string().optional(),
    Reciever_id: type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Transfer.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Transfer.ensureIndex('name');
Transfer.ensureIndex('createdAt');
Transfer.ensureIndex('editedAt');

Transfer.associate = models => {
    models.Transfer.belongsTo(models.User, 'sender', 'Sender_id', 'id');
    models.Transfer.belongsTo(models.User, 'reciever', 'Reciever_id', 'id');
};

export default Transfer;
