const thinky = require('../lib/thinky');

const type = thinky.type;

const User = thinky.createModel('User', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    firstname  : String,
    lastname   : String,
    nickname   : type.string().optional(),
    pin        : String,
    password   : String,
    recoverKey : type.string().default(''),
    mail       : String,
    credit     : Number,
    isTemporary: type.boolean().default(false),
    createdAt  : type.date().default(() => new Date()),
    editedAt   : Date,
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

User.pre('save', function preSave(next) {
    this.editedAt = new Date();

    this.firstname = this.firstname.toLowerCase();
    this.lastname  = this.lastname.toLowerCase();
    this.nickname  = this.nickname.toLowerCase();

    next();
});

User.ensureIndex('firstname');
User.ensureIndex('lastname');
User.ensureIndex('nickname');
User.ensureIndex('mail');
User.ensureIndex('recoverKey');
User.ensureIndex('createdAt');
User.ensureIndex('editedAt');

User.associate = (models) => {
    models.User.hasAndBelongsToMany(models.GroupPeriod, 'groupPeriods', 'id', 'id');
    models.User.hasAndBelongsToMany(models.Right, 'rights', 'id', 'id');
    models.User.hasMany(models.MeanOfLogin, 'meansOfLogin', 'id', 'User_id');
    models.User.hasMany(models.Purchase, 'purchases', 'id', 'Buyer_id');
    models.User.hasMany(models.Purchase, 'sells', 'id', 'Seller_id');
    models.User.hasMany(models.Reload, 'reloads', 'id', 'Buyer_id');
    models.User.hasMany(models.Reload, 'reloadsMade', 'id', 'Seller_id');
    models.User.hasMany(models.Transfer, 'transfers', 'id', 'Reciever_id');
    models.User.hasMany(models.Transfer, 'transfersMade', 'id', 'Sender_id');
};

module.exports = User;
